server:
  port: 8882
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bz?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MySQL
    generate-ddl: true
    show-sql: true
